// addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.9.0")
// addSbtPlugin("com.lightbend.conductr" % "sbt-conductr" % "2.7.2")
// addSbtPlugin("org.ensime" % "sbt-ensime" % "2.5.1")
// addSbtPlugin("com.github.hirofumi" % "sbt-amm" % "0.1.1")
